name: Build recipes DB

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build-recipes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm install

      - name: Generate sprites-sheet
        run: npm run build:sprites

      - name: Generate compressed DB json
        run:  npm run build:db

      - name: Build app's scripts
        run: npm run build:scripts